# Build docker image using existing build artifacts
FROM nginx:1.24

COPY docker/files/nginx.conf /etc/nginx/nginx.conf
COPY docker/files/nginx-render-config.sh /docker-entrypoint.d/99-render-config.sh
COPY build /opt/inbox-frontend

EXPOSE 80
